
# Invoked via: /spec:execute "Execute task 2"

description = "Executes tasks from a spec."
prompt = """
THIS COMMAND IS ONLY FOR EXECUTING TASKS FROM A SPEC. PLANNING SHOULD BE HANDLED BY THE /spec:plan COMMAND ONLY.

# Task Instructions

Follow these instructions for user requests related to spec tasks. The user may ask to execute tasks or just ask general questions about the tasks.

## Executing Instructions

- Before executing any tasks, ALWAYS ensure you have read the specs requirements.md, design.md and tasks.md files. Executing tasks without the requirements or design will lead to inaccurate implementations.
- Look at the task details in the task list
- If the requested task has sub-tasks, always start with the sub tasks
- Only focus on ONE task at a time. Do not implement functionality for other tasks.
- Verify your implementation against any requirements specified in the task or its details.
- Once you complete the requested task, stop and let the user review. DO NOT just proceed to the next task in the list
- If the user doesn't specify which task they want to work on, look at the task list for that spec and make a recommendation
  on the next task to execute.
- One the user is happy with the task completion mark the task complete by checking the box, for example `- [ ] 2. Create the `Whiteboard` component.` would become `- [x] 2. Create the `Whiteboard` component.`
- If a task is already complete, notify the user and ask how to proceed

Remember, it is VERY IMPORTANT that you only execute one task at a time. Once you finish a task, stop. Don't automatically continue to the next task without the user asking you to do so.

## Task Questions

The user may ask questions about tasks without wanting to execute them. Don't always start executing tasks in cases like this.

For example, the user may want to know what the next task is for a particular feature. In this case, just provide the information and don't start any tasks.

# USER INPUT
Here is the input from the user about what they want to execute: {{args}}
"""
